# Generated by Django 3.2.9 on 2021-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traintable',
            name='trainnum',
        ),
        migrations.AddField(
            model_name='traintable',
            name='train',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traintable',
            name='begintime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='traintable',
            name='endtime',
            field=models.DateTimeField(),
        ),
    ]
