# Generated by Django 3.2.9 on 2021-12-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainDB', '0002_auto_20211213_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traintable',
            options={'ordering': ['train'], 'verbose_name': '火车', 'verbose_name_plural': '车次'},
        ),
    ]
