# Generated by Django 3.2.9 on 2021-12-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeatDB', '0002_alter_seattable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seattable',
            options={},
        ),
    ]
