# Generated by Django 3.2.9 on 2021-12-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeatDB', '0003_alter_seattable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seattable',
            options={'ordering': ['seat'], 'verbose_name': '座位表', 'verbose_name_plural': '座位'},
        ),
    ]
