# Generated by Django 3.2.9 on 2021-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainTicketDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintable',
            name='trainnum',
            field=models.CharField(max_length=20),
        ),
    ]
