# Generated by Django 3.2.9 on 2021-12-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TrainDB', '0002_auto_20211213_2235'),
        ('SeatDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buytime', models.DateTimeField(auto_now_add=True)),
                ('seatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeatDB.seattable')),
                ('trainId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainDB.traintable')),
            ],
        ),
    ]
