# Generated by Django 3.2.9 on 2021-12-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketDB', '0002_tickettable_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettable',
            options={'ordering': ['userId'], 'verbose_name': '车票表', 'verbose_name_plural': '车票'},
        ),
    ]
