# Generated by Django 3.2.9 on 2021-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketDB', '0003_alter_tickettable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettable',
            name='price',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
