# Generated by Django 3.2.9 on 2021-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', 1), ('女', 2)], max_length=5),
        ),
    ]
