# Generated by Django 3.2.9 on 2021-12-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDB', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户'},
        ),
    ]
